/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
import type * as oracle from "./oracle";
export type { oracle };
import type * as permissions from "./permissions";
export type { permissions };
import type * as token from "./token";
export type { token };
