/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PermissionManaged } from "./PermissionManaged";
export type { PermissionManager } from "./PermissionManager";
