/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PermissionManaged__factory } from "./PermissionManaged__factory";
export { PermissionManager__factory } from "./PermissionManager__factory";
