/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  PermissionManaged,
  PermissionManagedInterface,
} from "../../../contracts/permissions/PermissionManaged";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
    ],
    name: "RestrictedAccess",
    type: "error",
  },
  {
    inputs: [],
    name: "authority",
    outputs: [
      {
        internalType: "contract IAuthority",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class PermissionManaged__factory {
  static readonly abi = _abi;
  static createInterface(): PermissionManagedInterface {
    return new Interface(_abi) as PermissionManagedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PermissionManaged {
    return new Contract(address, _abi, runner) as unknown as PermissionManaged;
  }
}
