/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1363ReceiverMock__factory } from "./ERC1363ReceiverMock__factory";
export { ERC20Mock__factory } from "./ERC20Mock__factory";
