/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1363ReceiverMock } from "./ERC1363ReceiverMock";
export type { ERC20Mock } from "./ERC20Mock";
